### ISSUE TITLE
Problems with view_CoRegPoints

### ISSUE THREAD

**Issue by notprime** [GFZ/arosics#16]
* arosics version: 1.8
* Python version: 3.8
* Operating System: Ubuntu

### Description
Hello,
I was trying to view the CoReg points after a local coregistration process, but I got the error

`xml.etree.ElementTree.ParseError: mismatched tag: line 117, column 2`

This also happens if I install arosics in a new conda env.

### What I Did
This is the script I was running:
```
kwargs = {'grid_res': 32,
                 'window_size': (256, 256),
                 'max_iter': 10,
                 'max_shift': 30,
                 'match_gsd': True,
                 'min_reliability': 50,
                 'path_out': path_pan_loc}

CRL = COREG_LOCAL(im_reference, im_target, **kwargs)
CRL.correct_shifts()
CRL.view_CoRegPoints(figsize=(15, 15), backgroundIm='ref')
```

This is the error I get:
```
/davinci-1/home/rmusto/.conda/envs/hs_env/bin/python /davinci-1/home/rmusto/PycharmProjects/hypersharpening/coreg.py

/davinci-1/home/rmusto/.conda/envs/hs_env/lib/python3.8/site-packages/arosics/CoReg_local.py:392: UserWarning: The reference image needs to be resampled because it has a row/column rotation in its map info which is not handled by AROSICS.

  warnings.warn(msg % 'reference')

Warping progress     |==================================================| 100.0% Complete  => 0:00:00

Automatically detected nodata value for GeoArray 'ang20210604t105418_rfl_v2z1_img_5_PAN': 0.0

Adapting the target image pixel grid to the one of the reference image for shift detection.

Warping progress     |==================================================| 100.0% Complete  => 0:00:00

Calculating footprint polygon and actual data corner coordinates for reference image...

Polygonize progress     |==================================================| 100.0% Complete  => 0:00:00

Bounding box of calculated footprint for reference image:

              (667314.3817088677, 4739976.667670526, 670940.0496435786, 4748233.188719088)

Calculating footprint polygon and actual data corner coordinates for image to be shifted...

Polygonize progress     |==================================================| 100.0% Complete  => 0:00:00

Bounding box of calculated footprint for image to be shifted:

              (662218.442915169, 4734830.719663396, 676055.9921223957, 4753379.136725916)

Matching window position (X,Y): 669150.1236861283/4744167.396058965

Initializing tie points grid...

Calculating tie point grid (1059 points) using 48 CPU cores...

              progress: |==================================================| 100.0% Complete  => 0:00:04

Found 922 matches.

Performing validity checks...

148 tie points flagged by level 1 filtering (reliability).

70 tie points flagged by level 2 filtering (SSIM).

88 tie points flagged by level 3 filtering (RANSAC)

674 valid tie points remain after filtering.

Correcting geometric shifts...

Translating progress |==================================================| 100.0% Complete  => 0:00:00

Warping progress     |==================================================| 100.0% Complete  => 0:00:00

Writing GeoArray of size (3708, 2766) to /davinci-1/work/rmusto/Datasets/AvirisNG_tests/path_to_save_pan_local_coreg.

Note: array has been downsampled to 442 x 1000 for faster visualization.

Traceback (most recent call last):

  File "/davinci-1/home/rmusto/PycharmProjects/hypersharpening/coreg.py", line 104, in <module>

    CRL.view_CoRegPoints(figsize=(15, 15), backgroundIm='ref')

  File "/davinci-1/home/rmusto/.conda/envs/hs_env/lib/python3.8/site-packages/arosics/CoReg_local.py", line 560, in view_CoRegPoints

    fig, ax = backgroundIm.show_map(figsize=figsize,

  File "/davinci-1/home/rmusto/.conda/envs/hs_env/lib/python3.8/site-packages/geoarray/baseclasses.py", line 1410, in show_map

    crs_in = get_cartopy_crs_from_epsg(gA2plot.epsg)

  File "/davinci-1/home/rmusto/.conda/envs/hs_env/lib/python3.8/site-packages/geoarray/baseclasses.py", line 1400, in get_cartopy_crs_from_epsg

    return ccrs_from_epsg(epsg_code)

  File "/davinci-1/home/rmusto/.conda/envs/hs_env/lib/python3.8/site-packages/cartopy/crs.py", line 2557, in epsg

    return cartopy._epsg._EPSGProjection(code)

  File "/davinci-1/home/rmusto/.conda/envs/hs_env/lib/python3.8/site-packages/cartopy/_epsg.py", line 43, in __init__

    projection = pyepsg.get(code)

  File "/davinci-1/home/rmusto/.conda/envs/hs_env/lib/python3.8/site-packages/pyepsg.py", line 288, in get

    root = ET.fromstring(xml)

  File "/davinci-1/home/rmusto/.conda/envs/hs_env/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML

    parser.feed(text)

xml.etree.ElementTree.ParseError: mismatched tag: line 117, column 2

 

Process finished with exit code 1
```

**Comment by danschef** [comment]
I cannot reproduce this here (running it on Python 3.11). Could you try to update your environment? Probably, the xml package coming from Python 3.8 is not compatible anymore with the latest version of arosics.

**Comment by danschef** [comment]
I close this now due to inactivity. Feel free to reopen if the issue persists with a fresh installation of arosics.
