### ISSUE TITLE
Timed out during polygonize operation

### ISSUE THREAD

**Issue by pbrotoisworo** [GFZ/arosics#8]
* arosics version: 1.7.6
* Python version: Python 3.8
* Operating System: Windows 8

### Description

I'm calculating X/Y shifts using large panchromatic images. It takes a long time to polygonize and it raises an error. 

I checked the `progress_mon.py` file and it seems that the Timer object still assigns something to the timeout variable despite the default variable being `None`. This error also happens when I set `progress=False`.

I created a temporary fix by changing the progress bar code in `progress_mon.py` to always ignore `Timer.timed_out`

### What I Did

```py
coreg = COREG(im_ref=temp_ras_ref, im_tgt=temp_ras_secondary, nodata=(0, 0))
coreg.calculate_spatial_shifts()

# Traceback
Polygonize progress     |==================================----------------| 67.0% Complete  => 0:00:14Traceback (most recent call last):
  File "C:\Users\Angelo\Miniconda3\envs\georef\lib\site-packages\py_tools_ds\processing\progress_mon.py", line 164, in __call__
    self.print_progress(percent01 * 100)
  File "C:\Users\Angelo\Miniconda3\envs\georef\lib\site-packages\py_tools_ds\processing\progress_mon.py", line 121, in print_progress
    raise KeyboardInterrupt()
KeyboardInterrupt
```

**Comment by michaldolnik** [comment]
I experienced the same problem....

**Comment by danschef** [comment]
Thanks for reporting. To be able to reproduce this, I would need some test data.

Possible reasons for a timeout during polygonizing are:
- very large input datasets
- very complex footprints of the input datasets
- nodata value incorrectly set or many nodata pixels within the image footprints

As a workaround, you could set the parameter `calc_corners` to False when calling the `COREG` or `COREG_LOCAL` classes or crop the input datasets to their overlap area.

**Comment by danschef** [comment]
I close this because without test data, I cannot reproduce it. Feel free to open again, if the problem persists.
